services:
  panel:
    build: .
    ports:
      - 127.0.0.1:3000:3000

  postgresql:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: oblong

volumes:
  postgres-data: