name: StandardRB

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: StandardRB Linter
      uses: obl-ong/standardrb-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
